Fix CI (release) build script CMake use
The current CI environment (Ubuntu Bionic) ships with CMake version
3.12.4 which does not support build directory creation.

Supports #8.

diff --git a/ci/build-release b/ci/build-release
--- a/ci/build-release
+++ b/ci/build-release
@@ -65,7 +65,15 @@ function build_release()
     local -r build_directory="$repository/build/release"
     local -r build_configuration="$repository/configuration/CMakeLists.txt.ci-build-release"
 
-    if ! cmake -C "$build_configuration" -S "$repository" -B "$build_directory"; then
+    if ! mkdir -p "$build_directory"; then
+        abort "build directory creation error(s)"
+    fi
+
+    if ! cd "$build_directory"; then
+        abort "working directory change error(s)"
+    fi
+
+    if ! cmake -C "$build_configuration" "$repository"; then
         abort "CMake initialization error(s)"
     fi
 
