Improve CI script error localization
Supports #8.

diff --git a/ci/static-analysis-shellcheck b/ci/static-analysis-shellcheck
--- a/ci/static-analysis-shellcheck
+++ b/ci/static-analysis-shellcheck
@@ -64,7 +64,9 @@ function static_analysis_shellcheck()
 {
     local scripts; mapfile -t scripts < <( git -C "$repository" ls-files | xargs -r -d '\n' -I '{}' find "$repository/{}" -executable ); readonly scripts
 
-    shellcheck "${scripts[@]}"
+    if ! shellcheck "${scripts[@]}"; then
+        abort "script error(s)"
+    fi
 }
 
 function main()
